### ISSUE TITLE
Better organization of *.cpp and *.h files

### ISSUE THREAD

**Issue by casey-c** [casey-c/egg#2]
We're going to have a lot of *.cpp and *.h files by the end of this project. Even with just a handful of templates out there so far, the main repo directory is already getting very messy. We should figure out how to make subdirectories for our header files and actual code files so that we can easily see what code goes with what. 

It looks fine in QtCreator since it automatically splits up the *.h files and *.cpp files for us, but as we start getting more classes we should consider subdividing it further. Also, it would be nice if the github repo had specific directories for header files and source files (like QtCreator has). That might involve some changes to the qmake project file, but it's definitely doable. We should go ahead and figure that out now while our project is small enough.

**Comment by youngcc3157** [comment]
At the moment, I created folders for each type of files and did some code change. It is a temporary way to organize messy files for now. So, if it should be organized with a different way then we can modify it later on.
