### ISSUE TITLE
Bug: Adding 2 statements back to back should work

### ISSUE THREAD

**Issue by casey-c** [casey-c/egg#21]
After adding a statement, the selected region is the statement itself. Since statements instantly return on an add() - (since statements can't have children of their own), it may be more intuitive to make any add calls run on the parent of the statement, so that the add then adds a new sibling instead.

**Comment by youngcc3157** [comment]
I made adding multiple statements back to back would work by letting add calls run on the parent (except the root) but it bothers me that now there are inconsistent ways of adding child node based on the type.

**Comment by casey-c** [comment]
I put the logic in the TreeNode class instead to make it more consistent. I'll close this issue for now, but I suspect I'll want to add support for adding a cut after a statement and making that a sibling too.
