### ISSUE TITLE
Tree Copy Constructors

### ISSUE THREAD

**Issue by casey-c** [casey-c/egg#9]
We need a function to copy TreeNodes and TreeStates. Since they all work with pointers, we need to make sure we manage allocations properly so a change on one state doesn't affect a different state.

**Comment by youngcc3157** [comment]
I have implemented copy function instead of copy constructors for better performance. I have not tested it yet so I will leave this issue opened for now.

**Comment by youngcc3157** [comment]
I have tested it. It works fine for now. If there is any need for this function to be modified then this issue can be reactivated but it is closed for now.
